### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by nemchik**
This is definitely worth testing more than I have. It seems to run for me but I'm not sure of EVERYTHING that should be happening here.

### CODE REVIEW

**Comment by theotherp** [comment]
Hey, thank you. Sorry, this kinda flew under my radar.

**Comment by nemchik** [comment]
No worries. I'm sure there's more updates already. I can do this again if needed. There's also things like greenkeeper that can update dependencies automatically and PR those changes for review.

**Comment by nemchik** [comment]
nevermind, i checked, there's nothing else that can be updated within semver right now. there are updates but some might involve breaking changes or code refactoring. Here's the list from `npm outdated`

```
Package                     Current  Wanted  Latest  Location 
grunt                         0.4.5   0.4.5   1.0.4  nzbhydra2
grunt-bower-concat            0.5.0   0.5.0   1.0.0  nzbhydra2
grunt-bower-task              0.4.0   0.4.0   0.5.0  nzbhydra2
grunt-contrib-clean           0.6.0   0.6.0   2.0.0  nzbhydra2
grunt-contrib-concat          0.5.1   0.5.1   1.0.1  nzbhydra2
grunt-contrib-copy            0.7.0   0.7.0   1.0.0  nzbhydra2
grunt-contrib-cssmin         0.12.3  0.12.3   3.0.0  nzbhydra2
grunt-contrib-less            1.4.1   1.4.1   2.0.0  nzbhydra2
grunt-contrib-uglify          0.9.2   0.9.2   4.0.1  nzbhydra2
grunt-contrib-watch           0.6.1   0.6.1   1.1.0  nzbhydra2
grunt-injector                0.6.1   0.6.1   1.1.0  nzbhydra2
grunt-ng-annotate             1.0.1   1.0.1   3.0.0  nzbhydra2
grunt-react                  0.10.0  0.10.0  0.12.3  nzbhydra2
grunt-shell                   1.3.1   1.3.1   3.0.1  nzbhydra2
gulp-angular-templatecache    2.2.7   2.2.7   3.0.0  nzbhydra2
gulp-changed                  1.3.2   1.3.2   4.0.2  nzbhydra2
gulp-clean                    0.3.2   0.3.2   0.4.0  nzbhydra2
gulp-clean-css               3.10.0  3.10.0   4.2.0  nzbhydra2
gulp-concat-css               2.3.0   2.3.0   3.1.0  nzbhydra2
gulp-copy                     0.0.2   0.0.2   4.0.1  nzbhydra2
gulp-flatten                  0.2.0   0.2.0   0.4.0  nzbhydra2
gulp-git                     1.15.1  1.15.1   2.9.0  nzbhydra2
gulp-inject                   3.0.0   3.0.0   5.0.4  nzbhydra2
gulp-install                  0.6.0   0.6.0   1.1.0  nzbhydra2
gulp-jsbeautifier             2.1.2   2.1.2   3.0.1  nzbhydra2
gulp-less                     3.5.0   3.5.0   4.0.1  nzbhydra2
gulp-livereload               3.8.1   3.8.1   4.0.2  nzbhydra2
gulp-load-plugins             1.6.0   1.6.0   2.0.1  nzbhydra2
gulp-newer                    0.5.2   0.5.2   1.4.0  nzbhydra2
gulp-print                    2.0.1   2.0.1   5.0.2  nzbhydra2
gulp-rev                      6.0.1   6.0.1   9.0.0  nzbhydra2
gulp-rev-all                 0.8.24  0.8.24   2.0.2  nzbhydra2
gulp-sequence                 0.4.6   0.4.6   1.0.0  nzbhydra2
gulp-sourcemaps              1.12.1  1.12.1   2.6.5  nzbhydra2
gulp-uglify                   1.5.4   1.5.4   3.0.2  nzbhydra2
gulp-watch                   4.3.11  4.3.11   5.0.1  nzbhydra2
merge-stream                  1.0.1   1.0.1   2.0.0  nzbhydra2
run-sequence                  1.2.2   1.2.2   2.2.1  nzbhydra2
wiredep                       2.2.2   2.2.2   4.0.0  nzbhydra2
```

**Comment by theotherp** [comment]
Thank you, I'll take a closer look soon.

**Comment by MindTooth** [comment]
Would not [Dependabot](https://dependabot.com) solve this more autonomous?  They are now part of GitHub, so a natural integration.

**Comment by nemchik** [comment]
I'm going to close this and encourage the use of dependabot.

**Pull request closed without merging**
