### PR TITLE
Added Indexer for NZBKing.com and beta.nzbindex.com

### PR DESCRIPTION
**Pull request by danielkastner**
Added Indexer for NZBKing.com (https://www.nzbking.com/; based on Code for Binsearch) and NZBIndex.com's BETA Site (https://beta.nzbindex.com/search)

### CODE REVIEW

**Comment by theotherp** [comment]
The first proper backend pull request in nearly six years! Whooo!

I'll try to take a look as soon as possible to give it the recognition it deserves ;-)

**Comment by theotherp** [comment]
Well done!

I fixed some things, namely:
* Frontend resources are located in `core/ui-src` and are compiled into the static folder. But the tooling is a hassle to get working and your changes were minimal enough that this wasn't a problem
* NzbIndex actually supports paging
* I fixed the maxage parameter for NzbIndex and made it always sort by age desc
* Improved the size detection for nzbindex 
* The connection check didn't work for nzbindex because it returns a 307 for the main page

I'll close this PR because I merged it into another branch but thanks again.

**Comment by John-Gee** [comment]
@theotherp you may want to add OP as an author to your commit. ;)

**Comment by theotherp** [comment]
OP is still in the history of the files as the original contributor. His commit just didn't close this issue.

https://github.com/theotherp/nzbhydra2/commit/43cf2cf7b6c6507e9bf119b57102f46de2351f20

But I didn't know about the co-author thing and added him.

**Comment by danielkastner** [comment]
Thanks for accepting my contribution and this project in general. Looking forward to the next release

**Comment by theotherp** [comment]
@danielkastner Already there: https://github.com/theotherp/nzbhydra2/releases/tag/v7.4.0

**Comment by albino1** [comment]
I wonder if this can be improved at all.  Maybe it could automatically filter the visible results to ones that contain the words in your search?  I like the idea of begin able to search NZBKing, but the amount of absolutely irrelevant trash and questionable content is incredible.  For example, searching for `walking dead s01e01` looks like this:

king

And that's a good result.  A lot of the time it's questionably legal porn or much, much, worse.

I'm not entirely sure how it generates the results, like is there a file called `walking dead s01e01` inside of a video game NZB?  Or it just matching one of those keywords and not all of them?

Right now you can just paste your search query into the results filter box, but I think it might make more sense to just effectively do that for NZBKing automatically for the user, which would then return results that look like this instead:

king2

**Comment by albino1** [comment]
I noticed that the Indexer Status always says there are 0 results (which is often correct) but then it still displays sometimes hundreds of results.  I'm sure you already fixed it, but I thought I would mention it in case it's related to why there's so many junk results.

king1b

king1

king2

**Pull request closed without merging**
