### PR TITLE
Update nzbhydra2wrapper.py

### PR DESCRIPTION
**Pull request by nemchik**
Used https://www.pythonconverter.com/

P.S. `REQUIRED_PYTHON` is set to 3.5 as it's the oldest non-EOL release on https://devguide.python.org/#status-of-python-branches

This may need some additional testing.

### CODE REVIEW

**Comment by theotherp** [comment]
I'll have to talk to the docker container maintainers first so that the containers don't break when I make a switch. Would probably be a good idea to have two files first.

**Comment by nemchik** [comment]
Two files is not a bad idea. If you have a preferred file name just let me know and i'll rename this file and not touch the existing one.

**Comment by nemchik** [comment]
BTW I've already got branches prepped for py3 for the LSIO image. I would need to adjust the filename for the wrapper used in them depending on this PR.

**Comment by theotherp** [comment]
I've updated the code you provided and already pushed it.

I'm not sure what updating the dockers to use Python 3 benefit right now, though. It works fine and I don't consider it a security risk in any way as it's containerized anyway...

But the containers would just need to run Python 3.4+ and use `nzbhydra2wrapperPy3.py`.

**Comment by nemchik** [comment]
My interest is upgrading because python 2.x is now EOL. I'll test with the new wrapper. Thanks.

**Comment by theotherp** [comment]
I know but that doesn't mean it ceases to exist...

**Pull request closed without merging**
